#ifndef BUTTONLAYOUTS_H_
#define BUTTONLAYOUTS_H_

#include "config.pb.h"
#include "enums.pb.h"
#include "gamepadmapping.h"

// Full-panel button layout element groups. Coordinates are authored for a
// 128x64 panel and scaled into the active viewport at draw time. Unlike
// GP2040-CE these are complete single-panel groups (no left/right split).

// Joystick / lever (digital dpad)
#define BUTTON_GROUP_ARCADE_STICK {{GP_ELEMENT_LEVER, {17, 37, 10, 10, 1, 0, 0}}}

// Stickless dpad (wasd / hitbox-style directions on the left)
#define BUTTON_GROUP_STICKLESS {\
	{GP_ELEMENT_DIR_BUTTON, {8,  20, 8, 8, 1, 1, GAMEPAD_MASK_LEFT,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_DIR_BUTTON, {26, 20, 8, 8, 1, 1, GAMEPAD_MASK_DOWN,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_DIR_BUTTON, {41, 29, 8, 8, 1, 1, GAMEPAD_MASK_RIGHT,   GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_DIR_BUTTON, {48, 53, 8, 8, 1, 1, GAMEPAD_MASK_UP,      GP_SHAPE_ELLIPSE}}\
}

// WASD box (square keyboard-style directions on the left)
#define BUTTON_GROUP_WASD_BOX {\
	{GP_ELEMENT_DIR_BUTTON, {8,  39, 18, 49, 1, 1, GAMEPAD_MASK_LEFT,  GP_SHAPE_SQUARE}},\
	{GP_ELEMENT_DIR_BUTTON, {19, 39, 29, 49, 1, 1, GAMEPAD_MASK_DOWN,  GP_SHAPE_SQUARE}},\
	{GP_ELEMENT_DIR_BUTTON, {19, 28, 29, 38, 1, 1, GAMEPAD_MASK_UP,    GP_SHAPE_SQUARE}},\
	{GP_ELEMENT_DIR_BUTTON, {30, 39, 40, 49, 1, 1, GAMEPAD_MASK_RIGHT, GP_SHAPE_SQUARE}}\
}

// 8 arcade buttons (right side)
#define BUTTON_GROUP_ARCADE_BUTTONS {\
	{GP_ELEMENT_BTN_BUTTON, {62, 28,  8,  8, 1, 1, GAMEPAD_MASK_B3,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {80, 24,  8,  8, 1, 1, GAMEPAD_MASK_B4,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {98, 24,  8,  8, 1, 1, GAMEPAD_MASK_R1,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {116,28,  8,  8, 1, 1, GAMEPAD_MASK_L1,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {57, 46,  8,  8, 1, 1, GAMEPAD_MASK_B1,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {75, 42,  8,  8, 1, 1, GAMEPAD_MASK_B2,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {93, 42,  8,  8, 1, 1, GAMEPAD_MASK_R2,    GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {111,46,  8,  8, 1, 1, GAMEPAD_MASK_L2,    GP_SHAPE_ELLIPSE}}\
}

// Vewlix arcade layout (8 buttons)
#define BUTTON_GROUP_VEWLIX {\
	{GP_ELEMENT_BTN_BUTTON, {57, 31, 8, 8, 1, 1, GAMEPAD_MASK_B3,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {75, 24, 8, 8, 1, 1, GAMEPAD_MASK_B4,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {93, 24, 8, 8, 1, 1, GAMEPAD_MASK_R1,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {111,24, 8, 8, 1, 1, GAMEPAD_MASK_L1,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {51, 49, 8, 8, 1, 1, GAMEPAD_MASK_B1,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {69, 42, 8, 8, 1, 1, GAMEPAD_MASK_B2,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {87, 42, 8, 8, 1, 1, GAMEPAD_MASK_R2,      GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {105,42, 8, 8, 1, 1, GAMEPAD_MASK_L2,      GP_SHAPE_ELLIPSE}}\
}

// Fightboard all-button layout (13 buttons, right side)
#define BUTTON_GROUP_FIGHTBOARD {\
	{GP_ELEMENT_BTN_BUTTON, {67, 27, 7, 7, 1, 1, GAMEPAD_MASK_B3,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {84, 18, 7, 7, 1, 1, GAMEPAD_MASK_B4,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {101,18, 7, 7, 1, 1, GAMEPAD_MASK_R1,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {118,18, 7, 7, 1, 1, GAMEPAD_MASK_L1,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {67, 43, 7, 7, 1, 1, GAMEPAD_MASK_B1,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {84, 35, 7, 7, 1, 1, GAMEPAD_MASK_B2,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {101,35, 7, 7, 1, 1, GAMEPAD_MASK_R2,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {118,35, 7, 7, 1, 1, GAMEPAD_MASK_L2,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {82, 47, 3, 3, 1, 1, GAMEPAD_MASK_L3,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {92, 47, 3, 3, 1, 1, GAMEPAD_MASK_S1,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {101,47, 3, 3, 1, 1, GAMEPAD_MASK_A1,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {110,47, 3, 3, 1, 1, GAMEPAD_MASK_S2,     GP_SHAPE_ELLIPSE}},\
	{GP_ELEMENT_BTN_BUTTON, {120,47, 3, 3, 1, 1, GAMEPAD_MASK_R3,     GP_SHAPE_ELLIPSE}}\
}

#endif